// Settings
:idprefix:
:idseparator: -
:page-component-title: Application de mMec
= {page-component-title}

[#summary]
== Sommaire

Application en ligne de commande servant à exécuter les commandes de l'API mMec.

[#usage]
== Utilisation

----
Usage: mmec-cli [-hV] -d=<jdbcUrl> [-f=<facadeType>] -i=<ontoRelId>
                -m=<mappingFile> -n=<databaseName> -o=<outputFilePath>
                -p=<password> -s=<mappingSchema> -t=<ontologyFile> -u=<username>
Command line interface for the MMec application.
  -d, --db-url=<jdbcUrl>   Database JDBC URL to the source database. The
                             database must be a PostgreSQL database and
                             contains the OntoRelCat.
  -f, --facade=<facadeType>
                           Type of facade to generate. Options: VIEWS, INSERTS.
                             Default: VIEWS.
  -h, --help               Show this help message and exit.
  -i, --id-ontorel=<ontoRelId>
                           OntoRel identifier in the OntoRelCat.
  -m, --mapping-file=<mappingFile>
                           Path to the mapping file.
  -n, --db-name=<databaseName>
                           Database name.
  -o, --output=<outputFilePath>
                           Output file for the facade.
  -p, --db-password=<password>
                           Database password.
  -s, --facade-schema=<mappingSchema>
                           Schema to use for the mapping.
  -t, --ontology-file=<ontologyFile>
                           Path to the ontology file.
  -u, --db-username=<username>
                           Database username.
  -V, --version            Print version information and exit.
----

[#examples]
== Exemples

Plusieurs exemples d'arrimage mMec sont disponibles dans le https://github.com/samdus/mmec-library/tree/main/src/test/resources/testset[dépôt du projet mMec].

Pour exécuter un exemple, il suffit de lancer une commande de cette façon:
----
mmec-cli --db-url="jdbc:postgresql://localhost:59385/test" \
         --db-name="test" \
         --db-username=test \
         --db-password=test \
         --ontology-file=src/test/resources/testset/coverage/ontology.ttl \
         --mapping-file=src/test/resources/testset/coverage/mapping.ttl \
         --facade-schema=facade \
         --id-ontorel=coverage \
         --facade=VIEWS \
         --output=facade-views.sql
----

[#installation]
. Récupérer la dernière version de l'https://github.com/samdus/mmec-cli/releases/download/1.0.0/mmec-cli-1.0.0.zip[artefact du projet].
. Dézipper le fichier mmec-cli-1.0.0.zip
. Les scripts mmec-cli pour Unix et mmec-cli.bat pour Windows sont maintenant disponible. Ces scripts se trouvent dans le répertoire /bin.

[#build]
Simple exécution de la tâche `construction` de Gradle. Pour générer le projet comme s'il s'agissait de la branche dev, exécuter la tâche `./gradlew construction -pFlow=dev`.

Afin de mettre à jour la distribution manuelle, exécuter la tâche `./gradlew majDistribution`.

[#licence]
== Copyright et licences

=== Copyright

Copyright 2018-{localyear}, https://www.linkedin.com/in/samueldussault/[Samuel Dussault]

Copyright 2018-{localyear}, https://www.usherbrooke.ca/informatique/nous-joindre/personnel/corps-professoral/professeurs/luc-lavoie[Luc Lavoie]

Copyright 2018-{localyear}, https://www.usherbrooke.ca/recherche/fr/specialistes/details/jean-francois.ethier[Jean-François Ethier]

Copyright 2018-{localyear}, https://www.usherbrooke.ca/informatique/nous-joindre/personnel/corps-professoral/professeurs/christina-khnaisser[Christina Khnaisser]

Copyright 2018-{localyear}, https://griis.ca/[GRIIS]

GRIIS (Groupe de recherche interdisciplinaire en informatique de la santé) +
Faculté des sciences et Faculté de médecine et sciences de la santé +
Université de Sherbrooke (Québec) J1K 2R1 +

CANADA

=== Licences
Le code de ce projet est sous licence link:LiLiQ-R11.txt[LILIQ-R]. Click here for the
link:LILIQ-R11EN.txt[English version].


